#define yyFlexLexer pascalFlexLexer
#define yywrap pascalwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <iostream>

using namespace std;

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int CopascalLexxer::yylex()


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 133
#define YY_END_OF_BUFFER 134
static yyconst short int yy_accept[463] =
    {   0,
        0,    0,    0,    0,  134,  132,  130,  131,  132,  132,
      121,    4,  109,  110,  119,  117,  103,  118,  104,  120,
      127,  102,  101,  113,  111,  115,  123,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  107,  108,
      124,  126,    1,  122,    8,    7,    8,  130,  125,  129,
        2,  105,    0,    0,  127,  106,  114,  112,  116,  126,
      126,  126,  126,   16,   69,  126,  126,  126,  126,  126,
      126,  126,   64,  126,  126,  126,  126,  126,  126,  126,
      126,  126,   59,  126,   17,   24,  126,  126,  126,  126,

      126,  126,   53,   19,   74,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,   65,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,   16,    0,
        0,  125,  129,    0,    3,  128,  126,   73,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,   70,  126,
      126,  126,   55,  126,  126,  126,  126,   85,  126,  126,
       62,  126,  126,  126,  126,  126,  126,  126,  126,   72,
       95,  126,   96,  126,   47,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,   43,   67,   68,
      126,  126,  126,  126,  126,   20,  126,  126,  126,  126,

       51,  126,  126,  126,  126,   75,    5,    0,    0,  126,
      126,  126,  126,   63,  126,  126,  126,  126,  126,  126,
      126,  126,   61,  126,  126,  126,  126,   46,  126,  126,
      126,   41,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
       29,  126,  126,  126,  126,  126,  126,   60,  126,   93,
       50,   26,  126,   79,  126,  126,   18,  126,    6,    0,
      128,  126,   52,  126,   58,   80,   40,   49,  126,  126,
      126,  126,  126,  126,  126,  126,   94,  126,  126,  126,
      126,  126,  126,  126,   10,  126,  126,  126,  126,  126,

      126,  126,  126,  126,  126,  126,  126,  126,   71,  126,
      126,  126,  126,  126,  126,  126,  126,   57,  126,   23,
       30,  126,  126,  126,  126,  126,   44,  126,   66,  126,
       21,   83,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,   27,  126,  126,   45,   88,  126,  126,
      126,  126,  126,   37,  126,  126,   54,  126,   56,  126,
      126,   32,  126,  126,  126,  126,  126,  126,   31,  126,
      126,   81,  126,  126,   22,   48,  126,  126,  126,  126,
      126,   89,  126,  126,  126,   38,  126,   76,  126,  126,
      126,  126,  126,  126,   92,  126,   82,  126,   13,  126,

      126,  126,  126,   84,  126,   77,  126,  126,  126,  126,
      126,   87,   86,  126,   35,  126,  126,   99,  126,   91,
      126,  126,   12,  126,  126,  126,  126,  126,   42,  126,
       28,   33,   78,   36,   39,  126,   11,  100,  126,   98,
      126,  126,  126,   34,  126,  126,   97,  126,  126,  126,
      126,   90,  126,   14,  126,  126,    9,  126,  126,   25,
       15,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    1,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,    1,   51,   52,   40,    1,   53,   25,   26,   27,

       28,   29,   30,   31,   32,   33,   34,   35,   54,   37,
       55,   39,   40,   41,   56,   43,   44,   45,   46,   47,
       48,   49,   57,   58,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    2,    3,    3,    3,    1,    1
    } ;

static yyconst short int yy_base[468] =
    {   0,
        0,    0,   56,   57,  585,  586,  582,  586,   45,    0,
      586,  586,  573,  586,  586,  586,  586,  586,  568,  566,
       49,  559,  586,   46,  586,  558,  586,   39,  550,   48,
       41,   53,   67,   32,    0,   73,   53,   66,   75,   87,
       73,   95,  109,  103,  101,  115,  104,   70,  586,  586,
      586,  124,  586,  586,  586,  586,  540,  574,  138,    0,
      586,  586,  572,   76,  155,  586,  586,  586,  586,    0,
      104,  547,  532,  108,    0,  542,  114,  543,  129,  533,
      134,  132,  523,  531,  117,  540,  152,  140,  148,  525,
      528,  521,    0,  524,  155,    0,  537,  137,  534,  525,

      157,  526,    0,    0,    0,  515,  529,  163,  165,  531,
      523,  170,  525,  510,  166,  172,  176,    0,   30,  513,
      179,  523,  509,  508,  516,  504,  514,  504,  170,  517,
      197,  212,    0,  540,  586,  214,  499,    0,  168,  513,
      508,  511,  512,  176,  183,  182,  494,  497,    0,  498,
      184,  506,    0,  505,  195,  504,  192,    0,  503,  191,
      484,  503,  198,  493,  499,  483,  497,  496,  196,    0,
        0,  495,    0,  494,    0,  480,  486,  493,  473,  215,
      482,  201,  489,  208,  478,  486,  485,    0,    0,    0,
      486,  470,  473,  481,  480,    0,  479,  463,  473,  205,

        0,  461,  468,  471,  458,    0,    0,  481,  249,  458,
      450,  213,  460,    0,  461,  213,  452,  450,  452,  460,
      448,  220,    0,  451,  448,  447,  459,    0,  451,  227,
      442,    0,  456,  442,  450,  440,  445,  235,  450,  452,
      229,  449,  244,  247,  448,  434,  446,  445,  440,  443,
      224,  429,  426,  248,  442,  249,  439,    0,  251,    0,
        0,    0,  431,    0,  421,  436,    0,  435,  586,  260,
      265,  254,    0,  437,    0,    0,    0,  420,  425,  415,
      256,  248,  426,  414,  413,  418,    0,  252,  413,  421,
      254,  420,  261,  422,    0,  420,  265,  406,  254,  416,

      420,  411,  402,  417,  267,  402,  416,  268,    0,  404,
      413,  398,  395,  272,  402,  409,  408,    0,  274,    0,
      257,  408,  398,  388,  388,  404,    0,  386,    0,  402,
        0,    0,  275,  378,  378,  398,  267,  396,  380,  387,
      282,  393,  376,    0,  287,  392,    0,    0,  390,  373,
      277,  373,  372,    0,  383,  378,    0,  277,    0,  377,
      376,    0,  365,  374,  371,  364,  378,  379,    0,  361,
      375,    0,  367,  292,    0,    0,  364,  363,  371,  366,
      371,    0,  361,  368,  366,    0,  352,    0,  344,  363,
      362,  341,  361,  352,    0,  293,    0,  351,    0,  344,

      341,  281,  342,    0,  339,    0,  338,  353,  330,  350,
      334,    0,    0,  348,    0,  348,  347,    0,  329,    0,
      331,  323,    0,  283,  329,  340,  336,  299,    0,  305,
        0,    0,    0,    0,    0,  331,    0,    0,  315,    0,
      306,  288,  311,    0,  310,  321,    0,  322,  310,  312,
      310,    0,  311,    0,  295,  296,    0,  300,   81,    0,
        0,  586,  359,   96,  361,   69,  364
    } ;

static yyconst short int yy_def[468] =
    {   0,
      462,    1,  463,  463,  462,  462,  462,  462,  462,  464,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  462,  462,
      462,  465,  462,  462,  462,  462,  462,  462,  462,  466,
      462,  462,  467,  462,  462,  462,  462,  462,  462,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,

      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  462,
      462,  462,  466,  467,  462,  462,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,

      465,  465,  465,  465,  465,  465,  465,  462,  462,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  462,  462,
      462,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,

      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,

      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,    0,  462,  462,  462,  462,  462
    } ;

static yyconst short int yy_nxt[645] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   35,   35,   37,   38,   39,   40,   41,   35,
       42,   43,   44,   45,   46,   47,   48,   35,   35,   49,
       50,   51,   52,   38,   40,   43,   53,   54,   56,   56,
       59,   59,   64,   71,   65,   65,   67,   68,   81,   92,
      133,   77,   82,  195,   78,   72,   97,  196,   83,   73,
       74,   75,   79,   57,   57,   80,   92,   85,   84,   86,
       88,  136,  136,   98,   74,   83,  108,   60,   89,   87,

       77,   93,   80,   99,   90,   97,  100,  128,   94,   95,
       91,  102,  101,  109,   96,  103,  110,  461,  111,   88,
       99,   90,  112,  104,  128,  108,   94,  105,   96,  101,
      106,  107,  113,  117,  125,  126,  114,  121,  123,  115,
      118,  131,  122,  119,  127,  137,  124,  111,   71,  140,
      120,  116,  144,  132,  132,  142,  122,  118,  152,  137,
       72,  113,  146,  140,   73,   74,   75,  123,   64,  142,
       65,   65,  152,  148,  157,  147,  149,  154,  169,  129,
      158,  144,  159,  172,  160,  165,  166,  148,  177,  147,
      155,  211,  169,  183,  156,  184,  179,  167,  191,  173,

      189,  185,  180,  193,  178,  218,  190,  222,  186,  192,
      198,  140,   59,   59,  229,  131,  194,  216,  178,  180,
      211,  199,  183,  207,  217,  140,  192,  132,  132,  136,
      136,  216,  225,  227,  218,  232,  222,  238,  217,  310,
      245,  209,  250,  229,  246,  252,  264,  227,  274,  225,
      289,  238,  232,  247,  277,  283,  250,  248,  296,  270,
      264,  270,  252,  299,  271,  271,  274,  302,  277,  300,
      303,  313,  315,  283,  317,  271,  271,  322,  310,  289,
      271,  271,  327,  334,  340,  329,  335,  296,  343,  338,
      351,  345,  328,  354,  365,  360,  302,  364,  373,  303,

      313,  315,  329,  317,  377,  381,  322,  338,  345,  355,
      384,  365,  388,  340,  393,  405,  421,  343,  425,  351,
      439,  377,  443,  355,  360,  449,  364,  373,  445,  448,
      388,  393,  458,  459,  381,  425,  460,  439,  457,  384,
      444,  456,  449,  455,  405,  421,  454,  453,  452,  458,
      459,  443,  451,  450,  444,  447,  446,  445,  448,   55,
       55,   55,   70,   70,  134,  134,  134,  442,  441,  440,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  424,  423,  422,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,

      406,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  392,  391,  390,  389,  387,  386,  385,  383,
      382,  380,  379,  378,  376,  375,  374,  372,  371,  370,
      369,  368,  367,  366,  363,  362,  361,  359,  358,  357,
      356,  353,  352,  350,  349,  348,  347,  346,  344,  342,
      341,  339,  337,  336,  333,  332,  331,  330,  326,  325,
      324,  323,  321,  320,  319,  318,  316,  314,  312,  311,
      309,  308,  307,  306,  305,  304,  301,  298,  297,  295,
      294,  293,  292,  291,  290,  288,  287,  286,  285,  284,
      282,  281,  280,  279,  278,  276,  275,  273,  272,  269,

      268,  267,  266,  265,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  251,  249,  244,  243,  242,
      241,  240,  239,  237,  236,  235,  234,  233,  231,  230,
      228,  226,  224,  223,  221,  220,  219,  215,  214,  213,
      212,  210,  135,  208,  206,  205,  204,  203,  202,  201,
      200,  197,  188,  187,  182,  181,  176,  175,  174,  171,
      170,  168,  164,  163,  162,  161,  153,  151,  150,  145,
      143,  141,  139,  138,  135,   58,  130,   76,   69,   66,
       63,   62,   61,   58,  462,    5,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,

      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462
    } ;

static yyconst short int yy_chk[645] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        9,    9,   21,   28,   21,   21,   24,   24,   31,   34,
      466,   30,   31,  119,   30,   28,   37,  119,   31,   28,
       28,   28,   30,    3,    4,   30,   34,   32,   31,   32,
       33,   64,   64,   38,   28,   31,   41,  464,   33,   32,

       30,   36,   30,   38,   33,   37,   39,   48,   36,   36,
       33,   40,   39,   41,   36,   40,   41,  459,   42,   33,
       38,   33,   42,   40,   48,   41,   36,   40,   36,   39,
       40,   40,   43,   44,   47,   47,   43,   45,   46,   43,
       44,   59,   45,   44,   47,   71,   46,   42,   52,   74,
       44,   43,   79,   59,   59,   77,   45,   44,   85,   71,
       52,   43,   81,   74,   52,   52,   52,   46,   65,   77,
       65,   65,   85,   82,   88,   81,   82,   87,   98,   52,
       88,   79,   89,  101,   89,   95,   95,   82,  108,   81,
       87,  139,   98,  112,   87,  112,  109,   95,  116,  101,

      115,  112,  109,  117,  108,  146,  115,  151,  112,  116,
      121,  129,  131,  131,  160,  132,  117,  144,  108,  109,
      139,  121,  112,  129,  145,  129,  116,  132,  132,  136,
      136,  144,  155,  157,  146,  163,  151,  169,  145,  251,
      180,  136,  182,  160,  180,  184,  200,  157,  212,  155,
      230,  169,  163,  180,  216,  222,  182,  180,  238,  209,
      200,  209,  184,  241,  209,  209,  212,  243,  216,  241,
      244,  254,  256,  222,  259,  270,  270,  272,  251,  230,
      271,  271,  281,  288,  293,  282,  288,  238,  297,  291,
      305,  299,  281,  308,  321,  314,  243,  319,  333,  244,

      254,  256,  282,  259,  337,  341,  272,  291,  299,  308,
      345,  321,  351,  293,  358,  374,  396,  297,  402,  305,
      424,  337,  428,  308,  314,  442,  319,  333,  430,  441,
      351,  358,  455,  456,  341,  402,  458,  424,  453,  345,
      428,  451,  442,  450,  374,  396,  449,  448,  446,  455,
      456,  428,  445,  443,  428,  439,  436,  430,  441,  463,
      463,  463,  465,  465,  467,  467,  467,  427,  426,  425,
      422,  421,  419,  417,  416,  414,  411,  410,  409,  408,
      407,  405,  403,  401,  400,  398,  394,  393,  392,  391,
      390,  389,  387,  385,  384,  383,  381,  380,  379,  378,

      377,  373,  371,  370,  368,  367,  366,  365,  364,  363,
      361,  360,  356,  355,  353,  352,  350,  349,  346,  343,
      342,  340,  339,  338,  336,  335,  334,  330,  328,  326,
      325,  324,  323,  322,  317,  316,  315,  313,  312,  311,
      310,  307,  306,  304,  303,  302,  301,  300,  298,  296,
      294,  292,  290,  289,  286,  285,  284,  283,  280,  279,
      278,  274,  268,  266,  265,  263,  257,  255,  253,  252,
      250,  249,  248,  247,  246,  245,  242,  240,  239,  237,
      236,  235,  234,  233,  231,  229,  227,  226,  225,  224,
      221,  220,  219,  218,  217,  215,  213,  211,  210,  208,

      205,  204,  203,  202,  199,  198,  197,  195,  194,  193,
      192,  191,  187,  186,  185,  183,  181,  179,  178,  177,
      176,  174,  172,  168,  167,  166,  165,  164,  162,  161,
      159,  156,  154,  152,  150,  148,  147,  143,  142,  141,
      140,  137,  134,  130,  128,  127,  126,  125,  124,  123,
      122,  120,  114,  113,  111,  110,  107,  106,  102,  100,
       99,   97,   94,   92,   91,   90,   86,   84,   83,   80,
       78,   76,   73,   72,   63,   58,   57,   29,   26,   22,
       20,   19,   13,    7,    5,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,

      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define INITIAL 0
#define ASMBLOCK 1

//#include <windows.h>
#include "stdafx.h"
#include "opascalParser.h"
#include "utils.h"

#define YY_SKIP_YYWRAP
#undef  YY_DECL
#define YY_DECL int CopascalLexxer::yylex(YYSTYPE *pascalval)
#define SETTOK(x) do { pascalval->name.node_type=x;pascalval->name.line=yylineno; pascalval->name.name =str_to_lower(_m_syntaxTree->duplicateString(yytext)); return x;} while(0)

#pragma warning(disable : 4244)

/* **** PASCAL KEYWORDS ****
threadvar 
assembler 
abstract  
finalization 
initialization 
as 
in 
with
on 
try 
except 
finally
while 
is
implementation 
unit 
object    
interface 
read 
write 
default 
stored 
nodefault 
implements
property  
protected 
public    
private   
published 
class     
goto      
inherited 
set         
packed      
file        
out         
forward     
const       
type        
var         
array       
of          
record      
end         
repeat      
until       
begin       
if          
then        
else        
for         
case        
do          
to          
downto      
shl 
shr 
at  
div 
raise
mod  
and         
or          
xor         
program     
function    
procedure   
uses        
cdecl       
register    
dynamic     
virtual     
export      
external    
far         
override    
overload    
pascal      
message     
reintroduce 
safecall    
stdcall     
true        
false       
nil         
not         
constructor 
destructor  
readonly
writeonly
*/

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;




	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 463 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 586 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
      int c;
      
      do
      {
        c = yyinput();
        if(c == '\n')
          yylineno++;         
      }
      while(c!='}');      
    }
	YY_BREAK
case 2:
YY_RULE_SETUP
{
        int  c;
        bool cont=true;

        c = yyinput();
        
        do
        {
          switch(c)
          {
            case '\n':
              yylineno++;
              c=yyinput();
            break;
            case '*':
              c=yyinput();
              if(c==')')
                cont = false;
            break;
            default:
              c=yyinput();
          }
        }
        while(cont);
      }
	YY_BREAK
case 3:
YY_RULE_SETUP
{
                 yylineno++;
               }
	YY_BREAK
case 4:
YY_RULE_SETUP
{
       std::string s;
     bool cont = true;
     int c;

     c = yyinput();

     do
     {
       switch(c)
     {
       case '\n':
         YY_FATAL_ERROR("invalid string");
       break;
       case '\'':
         c = yyinput();

       if(c!='\'')
         cont=false;
       else
       {
         s += c;
         c = yyinput();
       }
       break;
       default:
         s += c;
       c = yyinput();
     }
     }
     while(cont);

     unput(c);

       pascalval->name.node_type=TOK_STRING;
     pascalval->name.line=yylineno; 
     pascalval->name.name =_m_syntaxTree->duplicateString(s.c_str());
     return TOK_STRING;
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
BEGIN ASMBLOCK;
	YY_BREAK
case 6:
YY_RULE_SETUP
BEGIN INITIAL;
	YY_BREAK
case 7:
YY_RULE_SETUP
{ yylineno++;}
	YY_BREAK
case 8:
YY_RULE_SETUP
{}
	YY_BREAK
case 9:
YY_RULE_SETUP
{ SETTOK( TOK_DISPINTERFACE);}
	YY_BREAK
case 10:
YY_RULE_SETUP
{ SETTOK( TOK_LABEL);}
	YY_BREAK
case 11:
YY_RULE_SETUP
{ SETTOK( TOK_THREADVAR);}
	YY_BREAK
case 12:
YY_RULE_SETUP
{ SETTOK( TOK_ASSEMBLER);}
	YY_BREAK
case 13:
YY_RULE_SETUP
{ SETTOK( TOK_ABSTRACT);}
	YY_BREAK
case 14:
YY_RULE_SETUP
{ SETTOK( TOK_FINALIZATION);}
	YY_BREAK
case 15:
YY_RULE_SETUP
{ SETTOK( TOK_INITIALIZATION);}
	YY_BREAK
case 16:
YY_RULE_SETUP
{ SETTOK( TOK_AS);}
	YY_BREAK
case 17:
YY_RULE_SETUP
{ SETTOK( TOK_IN);}
	YY_BREAK
case 18:
YY_RULE_SETUP
{ SETTOK( TOK_WITH);}
	YY_BREAK
case 19:
YY_RULE_SETUP
{ SETTOK( TOK_ON);}
	YY_BREAK
case 20:
YY_RULE_SETUP
{ SETTOK( TOK_TRY);}
	YY_BREAK
case 21:
YY_RULE_SETUP
{ SETTOK( TOK_EXCEPT);}
	YY_BREAK
case 22:
YY_RULE_SETUP
{ SETTOK( TOK_FINALLY);}
	YY_BREAK
case 23:
YY_RULE_SETUP
{ SETTOK( TOK_WHILE);}
	YY_BREAK
case 24:
YY_RULE_SETUP
{ SETTOK( TOK_IS);}
	YY_BREAK
case 25:
YY_RULE_SETUP
{ SETTOK( TOK_IMPLEMENTATION);}
	YY_BREAK
case 26:
YY_RULE_SETUP
{ SETTOK( TOK_UNIT);}
	YY_BREAK
case 27:
YY_RULE_SETUP
{ SETTOK( TOK_OBJECT);}
	YY_BREAK
case 28:
YY_RULE_SETUP
{ SETTOK( TOK_INTERFACE);}
	YY_BREAK
case 29:
YY_RULE_SETUP
{ SETTOK( TOK_READ );}
	YY_BREAK
case 30:
YY_RULE_SETUP
{ SETTOK( TOK_WRITE );}
	YY_BREAK
case 31:
YY_RULE_SETUP
{ SETTOK( TOK_DEFAULT );}
	YY_BREAK
case 32:
YY_RULE_SETUP
{ SETTOK( TOK_STORED );}
	YY_BREAK
case 33:
YY_RULE_SETUP
{ SETTOK( TOK_NODEFAULT );}
	YY_BREAK
case 34:
YY_RULE_SETUP
{ SETTOK( TOK_IMPLEMENTS);}
	YY_BREAK
case 35:
YY_RULE_SETUP
{ SETTOK( TOK_PROPERTY);}
	YY_BREAK
case 36:
YY_RULE_SETUP
{ SETTOK( TOK_PROTECTED);}
	YY_BREAK
case 37:
YY_RULE_SETUP
{ SETTOK( TOK_PUBLIC);}
	YY_BREAK
case 38:
YY_RULE_SETUP
{ SETTOK( TOK_PRIVATE);}
	YY_BREAK
case 39:
YY_RULE_SETUP
{ SETTOK( TOK_PUBLISHED);}
	YY_BREAK
case 40:
YY_RULE_SETUP
{ SETTOK( TOK_CLASS);}
	YY_BREAK
case 41:
YY_RULE_SETUP
{ SETTOK( TOK_GOTO);}
	YY_BREAK
case 42:
YY_RULE_SETUP
{ SETTOK( TOK_INHERITED);}
	YY_BREAK
case 43:
YY_RULE_SETUP
{ SETTOK( TOK_SET);}
	YY_BREAK
case 44:
YY_RULE_SETUP
{ SETTOK( TOK_DISPID);}
	YY_BREAK
case 45:
YY_RULE_SETUP
{ SETTOK( TOK_PACKED);}
	YY_BREAK
case 46:
YY_RULE_SETUP
{ SETTOK( TOK_FILE);}
	YY_BREAK
case 47:
YY_RULE_SETUP
{ SETTOK( TOK_OUT);}
	YY_BREAK
case 48:
YY_RULE_SETUP
{ SETTOK( TOK_FORWARD );}
	YY_BREAK
case 49:
YY_RULE_SETUP
{ SETTOK( TOK_CONST);}
	YY_BREAK
case 50:
YY_RULE_SETUP
{ SETTOK( TOK_TYPE);}
	YY_BREAK
case 51:
YY_RULE_SETUP
{ SETTOK( TOK_VAR);}
	YY_BREAK
case 52:
YY_RULE_SETUP
{ SETTOK( TOK_ARRAY);}
	YY_BREAK
case 53:
YY_RULE_SETUP
{ SETTOK( TOK_OF);}
	YY_BREAK
case 54:
YY_RULE_SETUP
{ SETTOK( TOK_RECORD);}
	YY_BREAK
case 55:
YY_RULE_SETUP
{ SETTOK( TOK_END);}
	YY_BREAK
case 56:
YY_RULE_SETUP
{ SETTOK( TOK_REPEAT);}
	YY_BREAK
case 57:
YY_RULE_SETUP
{ SETTOK( TOK_UNTIL);}
	YY_BREAK
case 58:
YY_RULE_SETUP
{ SETTOK( TOK_BEGIN);}
	YY_BREAK
case 59:
YY_RULE_SETUP
{ SETTOK( TOK_IF);}
	YY_BREAK
case 60:
YY_RULE_SETUP
{ SETTOK( TOK_THEN);}
	YY_BREAK
case 61:
YY_RULE_SETUP
{ SETTOK( TOK_ELSE);}
	YY_BREAK
case 62:
YY_RULE_SETUP
{ SETTOK( TOK_FOR);}
	YY_BREAK
case 63:
YY_RULE_SETUP
{ SETTOK( TOK_CASE);}
	YY_BREAK
case 64:
YY_RULE_SETUP
{ SETTOK( TOK_DO);}
	YY_BREAK
case 65:
YY_RULE_SETUP
{ SETTOK( TOK_TO);}
	YY_BREAK
case 66:
YY_RULE_SETUP
{ SETTOK( TOK_DOWNTO);}
	YY_BREAK
case 67:
YY_RULE_SETUP
{ SETTOK( TOK_SHL);}
	YY_BREAK
case 68:
YY_RULE_SETUP
{ SETTOK( TOK_SHR);}
	YY_BREAK
case 69:
YY_RULE_SETUP
{ SETTOK( TOK_AT);}
	YY_BREAK
case 70:
YY_RULE_SETUP
{ SETTOK( TOK_DIV);}
	YY_BREAK
case 71:
YY_RULE_SETUP
{ SETTOK( TOK_RAISE);}
	YY_BREAK
case 72:
YY_RULE_SETUP
{ SETTOK( TOK_MOD);}
	YY_BREAK
case 73:
YY_RULE_SETUP
{ SETTOK( TOK_AND);}
	YY_BREAK
case 74:
YY_RULE_SETUP
{ SETTOK( TOK_OR);}
	YY_BREAK
case 75:
YY_RULE_SETUP
{ SETTOK( TOK_XOR);}
	YY_BREAK
case 76:
YY_RULE_SETUP
{ SETTOK( TOK_PROGRAM);}
	YY_BREAK
case 77:
YY_RULE_SETUP
{ SETTOK( TOK_FUNCTION);}
	YY_BREAK
case 78:
YY_RULE_SETUP
{ SETTOK( TOK_PROCEDURE);}
	YY_BREAK
case 79:
YY_RULE_SETUP
{ SETTOK( TOK_USES);}
	YY_BREAK
case 80:
YY_RULE_SETUP
{ SETTOK( TOK_CDECL );}
	YY_BREAK
case 81:
YY_RULE_SETUP
{ SETTOK( TOK_DYNAMIC );}
	YY_BREAK
case 82:
YY_RULE_SETUP
{ SETTOK( TOK_VIRTUAL);}
	YY_BREAK
case 83:
YY_RULE_SETUP
{ SETTOK( TOK_EXPORT );}
	YY_BREAK
case 84:
YY_RULE_SETUP
{ SETTOK( TOK_EXTERNAL );}
	YY_BREAK
case 85:
YY_RULE_SETUP
{ SETTOK( TOK_FAR );}
	YY_BREAK
case 86:
YY_RULE_SETUP
{ SETTOK( TOK_OVERRIDE);}
	YY_BREAK
case 87:
YY_RULE_SETUP
{ SETTOK( TOK_OVERLOAD );}
	YY_BREAK
case 88:
YY_RULE_SETUP
{ SETTOK( TOK_PASCAL );}
	YY_BREAK
case 89:
YY_RULE_SETUP
{ SETTOK( TOK_MESSAGE );}
	YY_BREAK
case 90:
YY_RULE_SETUP
{ SETTOK( TOK_REINTRODUCE );}
	YY_BREAK
case 91:
YY_RULE_SETUP
{ SETTOK( TOK_SAFECALL );}
	YY_BREAK
case 92:
YY_RULE_SETUP
{ SETTOK( TOK_STDCALL);}
	YY_BREAK
case 93:
YY_RULE_SETUP
{ SETTOK( TOK_TRUE);}
	YY_BREAK
case 94:
YY_RULE_SETUP
{ SETTOK( TOK_FALSE);}
	YY_BREAK
case 95:
YY_RULE_SETUP
{ SETTOK( TOK_NIL);}
	YY_BREAK
case 96:
YY_RULE_SETUP
{ SETTOK( TOK_NOT);}
	YY_BREAK
case 97:
YY_RULE_SETUP
{ SETTOK( TOK_CONSTRUCTOR);}
	YY_BREAK
case 98:
YY_RULE_SETUP
{ SETTOK( TOK_DESTRUCTOR);}
	YY_BREAK
case 99:
YY_RULE_SETUP
{ SETTOK(TOK_READONLY);}
	YY_BREAK
case 100:
YY_RULE_SETUP
{ SETTOK(TOK_WRITEONLY);}
	YY_BREAK
case 101:
YY_RULE_SETUP
{ SETTOK( TOK_SEMICOLON);}
	YY_BREAK
case 102:
YY_RULE_SETUP
{ SETTOK( TOK_COLON);}
	YY_BREAK
case 103:
YY_RULE_SETUP
{ SETTOK( TOK_COMMA);}
	YY_BREAK
case 104:
YY_RULE_SETUP
{ SETTOK( TOK_DOT);}
	YY_BREAK
case 105:
YY_RULE_SETUP
{ SETTOK( TOK_DOTDOT);}
	YY_BREAK
case 106:
YY_RULE_SETUP
{ SETTOK( TOK_ASSIGN);}
	YY_BREAK
case 107:
YY_RULE_SETUP
{ SETTOK( TOK_LBRACKET);}
	YY_BREAK
case 108:
YY_RULE_SETUP
{ SETTOK( TOK_RBRACKET);}
	YY_BREAK
case 109:
YY_RULE_SETUP
{ SETTOK( TOK_LPAREN);}
	YY_BREAK
case 110:
YY_RULE_SETUP
{ SETTOK( TOK_RPAREN);}
	YY_BREAK
case 111:
YY_RULE_SETUP
{ SETTOK( TOK_EQ);}
	YY_BREAK
case 112:
YY_RULE_SETUP
{ SETTOK( TOK_NE);}
	YY_BREAK
case 113:
YY_RULE_SETUP
{ SETTOK( TOK_LT);}
	YY_BREAK
case 114:
YY_RULE_SETUP
{ SETTOK( TOK_LE);}
	YY_BREAK
case 115:
YY_RULE_SETUP
{ SETTOK( TOK_GT);}
	YY_BREAK
case 116:
YY_RULE_SETUP
{ SETTOK( TOK_GE);}
	YY_BREAK
case 117:
YY_RULE_SETUP
{ SETTOK( TOK_PLUS);}
	YY_BREAK
case 118:
YY_RULE_SETUP
{ SETTOK( TOK_MINUS);}
	YY_BREAK
case 119:
YY_RULE_SETUP
{ SETTOK( TOK_STAR);}
	YY_BREAK
case 120:
YY_RULE_SETUP
{ SETTOK( TOK_SLASH);}
	YY_BREAK
case 121:
YY_RULE_SETUP
{ SETTOK( TOK_LAND);}
	YY_BREAK
case 122:
YY_RULE_SETUP
{ SETTOK( TOK_LOR);}
	YY_BREAK
case 123:
YY_RULE_SETUP
{ SETTOK( TOK_ADDR);}
	YY_BREAK
case 124:
YY_RULE_SETUP
{ SETTOK( TOK_DEREF);}
	YY_BREAK
case 125:
YY_RULE_SETUP
{ seq_to_str(yytext,pascalval);return TOK_STRING;}
	YY_BREAK
case 126:
YY_RULE_SETUP
{ SETTOK(TOK_IDENTIFIER);}
	YY_BREAK
case 127:
YY_RULE_SETUP
{ SETTOK(TOK_INTEGER);}
	YY_BREAK
case 128:
YY_RULE_SETUP
{ SETTOK(TOK_REAL);}
	YY_BREAK
case 129:
YY_RULE_SETUP
{ SETTOK( TOK_HEX);}
	YY_BREAK
case 130:
YY_RULE_SETUP
{ ; }
	YY_BREAK
case 131:
YY_RULE_SETUP
{ yylineno++; }
	YY_BREAK
case 132:
YY_RULE_SETUP
{ }
	YY_BREAK
case 133:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ASMBLOCK):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 463 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 463 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 462);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif


/*

'[^'\n]*'' {
               yyless(yyleng-1);
               yymore();
           }


'[^'\n]*' {
        yytext[yyleng-1]=0;
              SETTOK2(TOK_STRING);
              yytext[yyleng-1]=0x27;
              return TOK_STRING;
          }
*/